// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zkIB9ThDUviH7FFbE-skwZSaHHCAkyA',
    appId: '1:754971893832:android:9ea04fb60d7ff039c5f87d',
    messagingSenderId: '754971893832',
    projectId: 'classroombuddy-bc928',
    storageBucket: 'classroombuddy-bc928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGZOcWc-6K4s5hBCSu01bGghovUaRKAI',
    appId: '1:754971893832:ios:09839dcfcb2e4c4fc5f87d',
    messagingSenderId: '754971893832',
    projectId: 'classroombuddy-bc928',
    storageBucket: 'classroombuddy-bc928.firebasestorage.app',
    iosBundleId: 'com.example.classroombuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBatcc0a3RLjec673AffOU5PfZplph7vcI',
    appId: '1:754971893832:web:8157bb7d96360398c5f87d',
    messagingSenderId: '754971893832',
    projectId: 'classroombuddy-bc928',
    authDomain: 'classroombuddy-bc928.firebaseapp.com',
    storageBucket: 'classroombuddy-bc928.firebasestorage.app',
  );
}
